# Generated by Django 3.2 on 2022-11-10 13:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20221108_1321"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "genre_id"), name="film_work_genre"
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                fields=("film_work_id", "person_id", "role"),
                name="film_work_person_role",
            ),
        ),
    ]
